CREATE TABLE Protech_Posting (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  Sales_Number TEXT NOT NULL,
  Invoice TEXT NOT NULL,
  dollar_amount money NOT NULL,
  Commission_percentage_fraction decimal(5,4) NOT NULL,
  Commission_Amount INTEGER NOT NULL,
  PO_number TEXT NOT NULL,
  Customer TEXT NOT NULL,
  Territory TEXT NOT NULL,
  Vendor TEXT NOT NULL,
  Date_paid TIMESTAMPTZ NULL,
  Paid BOOLEAN DEFAULT FALSE
);


CREATE TABLE Protech_SalePerson (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  First_Name TEXT NOT NULL,
  Last_Name TEXT NOT NULL,
  CreatedDate TIMESTAMPTZ DEFAULT now() NOT NULL
);


CREATE TABLE Protech_Sales_commission_Hist (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  sales_person_id INTEGER REFERENCES Protech_SalePerson(id) ON DELETE CASCADE NOT NULL,
  posting_id INTEGER REFERENCES Protech_Posting(id) ON DELETE CASCADE NOT NULL,
  commission_Rate INTEGER NOT NULL,
  commission_amount money NOT NULL,
  created_date TIMESTAMPTZ DEFAULT now() NOT NULL
);