CREATE TABLE Protech_Posting (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  sales_Number TEXT NOT NULL,
  invoice TEXT NOT NULL,
  dollar_amount money NOT NULL,
  commission_percentage_fraction decimal(5,4) NOT NULL,
  commission_Amount INTEGER NOT NULL,
  PO_number TEXT NOT NULL,
  customer TEXT NOT NULL,
  territory TEXT NOT NULL,
  vendor TEXT NOT NULL,
  date_paid TIMESTAMPTZ NULL,
  paid BOOLEAN DEFAULT FALSE,
  created_date TIMESTAMPTZ DEFAULT now() NOT NULL
);


CREATE TABLE Protech_SalePerson (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_Name TEXT NOT NULL,
  last_Name TEXT NOT NULL,
  createdDate TIMESTAMPTZ DEFAULT now() NOT NULL
);


CREATE TABLE Protech_Sales_commission_Hist (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  sales_person_id INTEGER REFERENCES Protech_SalePerson(id) ON DELETE CASCADE NOT NULL,
  posting_id INTEGER REFERENCES Protech_Posting(id) ON DELETE CASCADE NOT NULL,
  commission_Rate INTEGER NOT NULL,
  commission_amount money NOT NULL,
  Created_date TIMESTAMPTZ DEFAULT now() NOT NULL
);